definitions
def07161242230e104993b72f75e3deef7b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | method methodClass theNonMetaClass]).
(#class -> ViQueryMapDefinition).
(#id -> #'07161242-230e-1049-93b7-2f75e3deef7b').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:method | method methodClass theNonMetaClass]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})