definitions
def05e20c0019c2b546be31ae5d98b374f1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | #text -> (method getSource, String cr)]).
(#class -> ViQueryMapDefinition).
(#id -> #'05e20c00-19c2-b546-be31-ae5d98b374f1').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 June 2014 11:14 am')})).
(#sourceCode -> '[:method | #text -> (method getSource, String cr)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})