definitions
def0ef356e72ba99e49a8996f24e6c8fda2
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj hResizing]).
(#class -> ViQueryMapDefinition).
(#id -> #'0ef356e7-2ba9-9e49-a899-6f24e6c8fda2').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:06:25 pm')})).
(#sourceCode -> '[:obj | obj hResizing]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})