definitions
def0500ed1b71282d43b30789fd1223197d
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | ref compiledMethod]).
(#class -> ViQueryMapDefinition).
(#id -> #'0500ed1b-7128-2d43-b307-89fd1223197d').
(#inputKind -> MethodReference).
(#mapType -> #each).
(#outputKind -> CompiledMethod).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:45:19 pm')})).
(#sourceCode -> '[:ref | ref compiledMethod]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})