definitions
def1ea1492c4d46fd419ca65dda748f6e96
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'28 May 2015 10:20:48 am'); yourself)); add: (#id->#'1ea1492c-4d46-fd41-9ca6-5dda748f6e96'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 311@216).
	#current -> #'ce6ad922-f4f3-a043-ba74-a843f21c5238'.
	#scripts -> #(#'ce6ad922-f4f3-a043-ba74-a843f21c5238' ).
	#id -> #'a3540596-eb5d-e042-9fa2-e08cd46b4313'.
	#out -> #(#(#interactive #'4c709d76-8a49-864d-a885-75ea3af4e983' ) #(#interactive #'81872d25-bf17-4b41-846f-ce79bb65ee90' ) ).
	#in -> #().
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 311@216).
	#current -> #''ce6ad922-f4f3-a043-ba74-a843f21c5238''.
	#scripts -> #(#''ce6ad922-f4f3-a043-ba74-a843f21c5238'' ).
	#id -> #''a3540596-eb5d-e042-9fa2-e08cd46b4313''.
	#out -> #(#(#interactive #''4c709d76-8a49-864d-a885-75ea3af4e983'' ) #(#interactive #''81872d25-bf17-4b41-846f-ce79bb65ee90'' ) ).
	#in -> #().
}] value]'); yourself)