definitions
def1cfcb90aec5e7e48b1531ea3ce6c1baf
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out addAll: OhmSyntaxTestCase allSubclasses]).
(#class -> ViQueryStepDefinition).
(#id -> #'1cfcb90a-ec5e-7e48-b153-1ea3ce6c1baf').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'659e6db8-dc7d-144e-9522-a6328ba85d18').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm')})).
(#sourceCode -> '[:in :out | out addAll: OhmSyntaxTestCase allSubclasses]')})