definitions
def1ea1492c4d46fd419ca65dda748f6e96
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #'a3540596-eb5d-e042-9fa2-e08cd46b4313' ) ).
	#out -> #(#(#interactive #'4c709d76-8a49-864d-a885-75ea3af4e983' ) ).
	#scripts -> #(#GramadaGrammarRuleBrowser ).
	#id -> #'81872d25-bf17-4b41-846f-ce79bb65ee90'.
	#bounds -> (208@0 corner: 390@250).
	#current -> #GramadaGrammarRuleBrowser.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'1ea1492c-4d46-fd41-9ca6-5dda748f6e96').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:20:48 am')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #''a3540596-eb5d-e042-9fa2-e08cd46b4313'' ) ).
	#out -> #(#(#interactive #''4c709d76-8a49-864d-a885-75ea3af4e983'' ) ).
	#scripts -> #(#GramadaGrammarRuleBrowser ).
	#id -> #''81872d25-bf17-4b41-846f-ce79bb65ee90''.
	#bounds -> (208@0 corner: 390@250).
	#current -> #GramadaGrammarRuleBrowser.
}] value]')})