definitions
def16098badc8bf434ea06d18cd2a87edf8
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objects | objects]).
(#class -> ViQueryMapDefinition).
(#id -> #'16098bad-c8bf-434e-a06d-18cd2a87edf8').
(#inputKind -> Object).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 November 2014 5:03:59 pm')})).
(#sourceCode -> '[:objects | objects]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})