definitions
def24bf9bee27659c47bee307990a61c4a5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj listDirection]).
(#class -> ViQueryMapDefinition).
(#id -> #'24bf9bee-2765-9c47-bee3-07990a61c4a5').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:08:07 pm')})).
(#sourceCode -> '[:obj | obj listDirection]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})