definitions
def3d30f84866236f4bb599ca6fffd99810
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:p1 :p2 | p1 baseName asLowercase <= p2 baseName asLowercase]).
(#class -> ViQueryMapDefinition).
(#id -> #'3d30f848-6623-6f4b-b599-ca6fffd99810').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:p1 :p2 | p1 baseName asLowercase <= p2 baseName asLowercase]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})