definitions
def362ab341ab1e4a4c9c0114acc2ed3e86
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #(#(#interactive #'4c709d76-8a49-864d-a885-75ea3af4e983' ) #(#interactive #'81872d25-bf17-4b41-846f-ce79bb65ee90' ) ).
	#scripts -> #(#'ce6ad922-f4f3-a043-ba74-a843f21c5238' ).
	#id -> #'a3540596-eb5d-e042-9fa2-e08cd46b4313'.
	#bounds -> (1@0 corner: 203@250).
	#current -> #'ce6ad922-f4f3-a043-ba74-a843f21c5238'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'362ab341-ab1e-4a4c-9c01-14acc2ed3e86').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:46 am')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #(#(#interactive #''4c709d76-8a49-864d-a885-75ea3af4e983'' ) #(#interactive #''81872d25-bf17-4b41-846f-ce79bb65ee90'' ) ).
	#scripts -> #(#''ce6ad922-f4f3-a043-ba74-a843f21c5238'' ).
	#id -> #''a3540596-eb5d-e042-9fa2-e08cd46b4313''.
	#bounds -> (1@0 corner: 203@250).
	#current -> #''ce6ad922-f4f3-a043-ba74-a843f21c5238''.
}] value]')})