definitions
def3994d384d109e44e8b929a64780ce685
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj vResizing]).
(#class -> ViQueryMapDefinition).
(#id -> #'3994d384-d109-e44e-8b92-9a64780ce685').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:06:28 pm')})).
(#sourceCode -> '[:obj | obj vResizing]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})