definitions
def42833415c0c15547a2d42379c3d211c3
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:objs | objs collect: [:obj | #root -> obj]]).
(#class -> ViQueryMapDefinition).
(#id -> #'42833415-c0c1-5547-a2d4-2379c3d211c3').
(#inputKind -> ProtoObject).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:objs | objs collect: [:obj | #root -> obj]]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})