definitions
def455ad2d30d117742930183c3bf906e8b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj1 :obj2 | obj1 value <= obj2 value]).
(#class -> ViQueryMapDefinition).
(#id -> #'455ad2d3-0d11-7742-9301-83c3bf906e8b').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj1 :obj2 | obj1 value <= obj2 value]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})