definitions
def58aeeb1302da4545bbde10445a493d2d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'d8ede531-2596-da41-9224-a23bb2ff44d4'); add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'1 June 2015 1:30:44 pm'); yourself)); add: (#id->#'58aeeb13-02da-4545-bbde-10445a493d2d'); add: (#block->[:in :out | in do: [:obj | (out identityIncludes: obj) ifFalse: [out add: obj]]]); add: (#sourceCode->'[:in :out | in do: [:obj | (out identityIncludes: obj) ifFalse: [out add: obj]]]'); yourself)