definitions
def652273fd65965b44bfe1431c6aa636e1
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #'61bf820b-36b7-4a42-b552-e5e4394c909a' ) ).
	#out -> #().
	#scripts -> #(#'d1125580-8a80-594f-a31e-9a41d7c710a3' ).
	#id -> #'10c640bd-44ec-d848-a16f-d69ef7f445e9'.
	#bounds -> (1@432 corner: 735@604).
	#current -> #'d1125580-8a80-594f-a31e-9a41d7c710a3'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'652273fd-6596-5b44-bfe1-431c6aa636e1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:12:58 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #''61bf820b-36b7-4a42-b552-e5e4394c909a'' ) ).
	#out -> #().
	#scripts -> #(#''d1125580-8a80-594f-a31e-9a41d7c710a3'' ).
	#id -> #''10c640bd-44ec-d848-a16f-d69ef7f445e9''.
	#bounds -> (1@432 corner: 735@604).
	#current -> #''d1125580-8a80-594f-a31e-9a41d7c710a3''.
}] value]')})