definitions
def65fe476b3cd699488d49ec4ec931d81c
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | [OhmSyntaxTestCase allSubclasses] value in: [:result |
	out addAll: result asList]]).
(#class -> ViQueryStepDefinition).
(#id -> #'65fe476b-3cd6-9948-8d49-ec4ec931d81c').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'ce86de4b-e09e-0c4c-bde6-154468255070').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm')})).
(#sourceCode -> '[:in :out | [OhmSyntaxTestCase allSubclasses] value in: [:result |
	out addAll: result asList]]')})