definitions
def6a9db3f020aed541bded40c32e0a065a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:node | #text -> node formattedCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'6a9db3f0-20ae-d541-bded-40c32e0a065a').
(#inputKind -> RBProgramNode).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:node | #text -> node formattedCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})