definitions
def73e8373651448f47ba713ddb8ee006e5
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:classes | classes, (classes gather: [:cls | cls allSubclasses])]).
(#class -> ViQueryMapDefinition).
(#id -> #'73e83736-5144-8f47-ba71-3ddb8ee006e5').
(#inputKind -> ClassDescription).
(#mapType -> #all).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:classes | classes, (classes gather: [:cls | cls allSubclasses])]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})