definitions
def7fbeb02017a5a44b8452d00317b036af
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | RBParser parseMethod: method getSource asString]).
(#class -> ViQueryMapDefinition).
(#id -> #'7fbeb020-17a5-a44b-8452-d00317b036af').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> RBProgramNode).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:44:36 pm')})).
(#sourceCode -> '[:method | RBParser parseMethod: method getSource asString]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})