definitions
def7f5468a31dc7134092124ad1ee77effc
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj class name]).
(#class -> ViQueryMapDefinition).
(#id -> #'7f5468a3-1dc7-1340-9212-4ad1ee77effc').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:06:08 pm')})).
(#sourceCode -> '[:obj | obj class name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})