definitions
def81d4bba3fa925a449759d980ccef208a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | #text -> (obj methodClass organization categoryOfElement: obj selector)]).
(#class -> ViQueryMapDefinition).
(#id -> #'81d4bba3-fa92-5a44-9759-d980ccef208a').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:obj | #text -> (obj methodClass organization categoryOfElement: obj selector)]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})