definitions
def80ccb73755a36440b360f02ac53f3684
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #outer ) ).
	#out -> #(#(#interactive #outer ) ).
	#scripts -> #(#'b675a2ad-abbe-4349-9091-add2414ff6b3' ).
	#id -> #'f4a2969b-3eb2-cf47-b028-b64f4b6f94df'.
	#bounds -> (1@22 corner: 365@411).
	#current -> #'b675a2ad-abbe-4349-9091-add2414ff6b3'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'80ccb737-55a3-6440-b360-f02ac53f3684').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'9673ba1d-e332-5046-a986-2afaa7fd5197').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #outer ) ).
	#out -> #(#(#interactive #outer ) ).
	#scripts -> #(#''b675a2ad-abbe-4349-9091-add2414ff6b3'' ).
	#id -> #''f4a2969b-3eb2-cf47-b028-b64f4b6f94df''.
	#bounds -> (1@22 corner: 365@411).
	#current -> #''b675a2ad-abbe-4349-9091-add2414ff6b3''.
}] value]')})