definitions
def804d1524a7391b46808a044f2c24b914
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #().
	#scripts -> #(#'cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61' ).
	#id -> #'d3462818-9a09-b949-adaa-4d33bedaad6b'.
	#bounds -> (1@1 corner: 365@17).
	#current -> #'cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'804d1524-a739-1b46-808a-044f2c24b914').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'4e81d6d5-0abd-584f-a7fd-dbae7c6f8b7a').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #().
	#scripts -> #(#''cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61'' ).
	#id -> #''d3462818-9a09-b949-adaa-4d33bedaad6b''.
	#bounds -> (1@1 corner: 365@17).
	#current -> #''cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61''.
}] value]')})