definitions
def95a9b7d51a247f4a85961382081a5673
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | method methodReference]).
(#class -> ViQueryMapDefinition).
(#id -> #'95a9b7d5-1a24-7f4a-8596-1382081a5673').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 October 2014 2:56:56 pm')})).
(#sourceCode -> '[:method | method methodReference]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})