definitions
def9f165395722b6b41979e695440a8254b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:node | #text -> node class]).
(#class -> ViQueryMapDefinition).
(#id -> #'9f165395-722b-6b41-979e-695440a8254b').
(#inputKind -> RBProgramNode).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:node | #text -> node class]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})