definitions
def947580aed1f52f4c9c336314c8d48f67
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | ViQueryOrganizer default allCallsOn: symbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'947580ae-d1f5-2f4c-9c33-6314c8d48f67').
(#inputKind -> ByteSymbol).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '4 December 2013 8:34:54 am')})).
(#sourceCode -> '[:symbol | ViQueryOrganizer default allCallsOn: symbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})