definitions
def9bce5100007e7d43afd23d20862ff9a9
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #'a0ba2335-4cf5-8d40-b25c-759a9339163e' ) ).
	#out -> #(#(#interactive #'10c640bd-44ec-d848-a16f-d69ef7f445e9' ) ).
	#scripts -> #(#ohmDebuggerRuleInvocationsView ).
	#id -> #'61bf820b-36b7-4a42-b552-e5e4394c909a'.
	#bounds -> (1@101 corner: 735@406).
	#current -> #ohmDebuggerRuleInvocationsView.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'9bce5100-007e-7d43-afd2-3d20862ff9a9').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:10:35 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #''a0ba2335-4cf5-8d40-b25c-759a9339163e'' ) ).
	#out -> #(#(#interactive #''10c640bd-44ec-d848-a16f-d69ef7f445e9'' ) ).
	#scripts -> #(#ohmDebuggerRuleInvocationsView ).
	#id -> #''61bf820b-36b7-4a42-b552-e5e4394c909a''.
	#bounds -> (1@101 corner: 735@406).
	#current -> #ohmDebuggerRuleInvocationsView.
}] value]')})