definitions
def99ba75b7c1fb0048beadf60c9634619d
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'9 June 2015 1:56:49 pm'); yourself)); add: (#id->#'99ba75b7-c1fb-0048-bead-f60c9634619d'); add: (#block->[:in :out | out addAll: ([:arrayedCollection | arrayedCollection reject: [:e | e isNil ]] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:arrayedCollection | arrayedCollection reject: [:e | e isNil ]] value: in)]'); yourself)