definitions
def9100cc23b8b1fa48a4ac86f413bfff4b
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #(#(#interactive #'4c709d76-8a49-864d-a885-75ea3af4e983' ) ).
	#scripts -> #(#'1bccd250-6819-924d-9c65-aecfa8e24162' ).
	#id -> #'71a127f2-bbe0-dc41-9574-bc5028526009'.
	#bounds -> (1@255 corner: 390@389).
	#current -> #'1bccd250-6819-924d-9c65-aecfa8e24162'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'9100cc23-b8b1-fa48-a4ac-86f413bfff4b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:48 am')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #().
	#out -> #(#(#interactive #''4c709d76-8a49-864d-a885-75ea3af4e983'' ) ).
	#scripts -> #(#''1bccd250-6819-924d-9c65-aecfa8e24162'' ).
	#id -> #''71a127f2-bbe0-dc41-9574-bc5028526009''.
	#bounds -> (1@255 corner: 390@389).
	#current -> #''1bccd250-6819-924d-9c65-aecfa8e24162''.
}] value]')})