definitions
def9aa298c2a22e2e4383cd8859357e0c7a
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:cls1 :cls2 | cls2 allSuperclasses includes: cls1]).
(#class -> ViQueryMapDefinition).
(#id -> #'9aa298c2-a22e-2e43-83cd-8859357e0c7a').
(#inputKind -> Object).
(#mapType -> #twoArgs).
(#outputKind -> Boolean).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:cls1 :cls2 | cls2 allSuperclasses includes: cls1]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})