definitions
defa3a0aaa71711094f8621bac1067b8ab0
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | SystemNavigation default allCallsOn: symbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'a3a0aaa7-1711-094f-8621-bac1067b8ab0').
(#inputKind -> ByteSymbol).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:symbol | SystemNavigation default allCallsOn: symbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})