definitions
defbd42b84be2e03f449361626b76d2721f
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:obj | obj layoutPolicy class name]).
(#class -> ViQueryMapDefinition).
(#id -> #'bd42b84b-e2e0-3f44-9361-626b76d2721f').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:07:16 pm')})).
(#sourceCode -> '[:obj | obj layoutPolicy class name]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})