definitions
defbaae03672eb92745b6afc747b95925ac
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:method | method methodReference]).
(#class -> ViQueryMapDefinition).
(#id -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#inputKind -> CompiledMethod).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:49:39 pm')})).
(#sourceCode -> '[:method | method methodReference]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})