definitions
defc6a7a92306d5ae42b6ceedf36178c3bf
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #'a0ba2335-4cf5-8d40-b25c-759a9339163e' ) ).
	#out -> #().
	#scripts -> #(#'6494b430-72e5-4a44-b03e-56da9dcd8e3d' ).
	#id -> #'bf6db899-802f-2f43-b34d-1439eee5380a'.
	#bounds -> (1@1 corner: 735@96).
	#current -> #'6494b430-72e5-4a44-b03e-56da9dcd8e3d'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'c6a7a923-06d5-ae42-b6ce-edf36178c3bf').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:10:29 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#automatic #''a0ba2335-4cf5-8d40-b25c-759a9339163e'' ) ).
	#out -> #().
	#scripts -> #(#''6494b430-72e5-4a44-b03e-56da9dcd8e3d'' ).
	#id -> #''bf6db899-802f-2f43-b34d-1439eee5380a''.
	#bounds -> (1@1 corner: 735@96).
	#current -> #''6494b430-72e5-4a44-b03e-56da9dcd8e3d''.
}] value]')})