definitions
defc6a7a92306d5ae42b6ceedf36178c3bf
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'27 May 2015 6:10:29 pm'); yourself)); add: (#id->#'c6a7a923-06d5-ae42-b6ce-edf36178c3bf'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@101 corner: 735@406).
	#current -> #ohmDebuggerRuleInvocationsView.
	#scripts -> #(#ohmDebuggerRuleInvocationsView ).
	#id -> #'61bf820b-36b7-4a42-b552-e5e4394c909a'.
	#out -> #(#(#interactive #'10c640bd-44ec-d848-a16f-d69ef7f445e9' ) ).
	#in -> #(#(#automatic #'a0ba2335-4cf5-8d40-b25c-759a9339163e' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@101 corner: 735@406).
	#current -> #ohmDebuggerRuleInvocationsView.
	#scripts -> #(#ohmDebuggerRuleInvocationsView ).
	#id -> #''61bf820b-36b7-4a42-b552-e5e4394c909a''.
	#out -> #(#(#interactive #''10c640bd-44ec-d848-a16f-d69ef7f445e9'' ) ).
	#in -> #(#(#automatic #''a0ba2335-4cf5-8d40-b25c-759a9339163e'' ) ).
}] value]'); yourself)