definitions
defc3876e0215ba414aae61c41de8ba4e72
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:symbol | SystemNavigation default allImplementorsOf: symbol]).
(#class -> ViQueryMapDefinition).
(#id -> #'c3876e02-15ba-414a-ae61-c41de8ba4e72').
(#inputKind -> ByteSymbol).
(#mapType -> #each).
(#outputKind -> MethodReference).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:symbol | SystemNavigation default allImplementorsOf: symbol]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})