definitions
defcfeaece5e6ec3a449e8be84b31e5ed0e
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:ref | #text -> ref sourceCode]).
(#class -> ViQueryMapDefinition).
(#id -> #'cfeaece5-e6ec-3a44-9e8b-e84b31e5ed0e').
(#inputKind -> MethodReference).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '2 June 2014 6:14:25 pm')})).
(#sourceCode -> '[:ref | #text -> ref sourceCode]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})