definitions
defd1a31df669aa9f429638bf514aade0ae
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:node | node children]).
(#class -> ViQueryMapDefinition).
(#id -> #'d1a31df6-69aa-9f42-9638-bf514aade0ae').
(#inputKind -> Object).
(#mapType -> #each).
(#outputKind -> Object).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm')})).
(#sourceCode -> '[:node | node children]').
(#updateClearDefinition -> nil).
(#updateSetDefinition -> nil)})