definitions
defe6d693eaf2d41d439c6ecec536fe9ccd
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'27 May 2015 6:12:08 pm'); yourself)); add: (#id->#'e6d693ea-f2d4-1d43-9c6e-cec536fe9ccd'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 735@96).
	#current -> #'6494b430-72e5-4a44-b03e-56da9dcd8e3d'.
	#scripts -> #(#'6494b430-72e5-4a44-b03e-56da9dcd8e3d' ).
	#id -> #'bf6db899-802f-2f43-b34d-1439eee5380a'.
	#out -> #().
	#in -> #(#(#automatic #'a0ba2335-4cf5-8d40-b25c-759a9339163e' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@1 corner: 735@96).
	#current -> #''6494b430-72e5-4a44-b03e-56da9dcd8e3d''.
	#scripts -> #(#''6494b430-72e5-4a44-b03e-56da9dcd8e3d'' ).
	#id -> #''bf6db899-802f-2f43-b34d-1439eee5380a''.
	#out -> #().
	#in -> #(#(#automatic #''a0ba2335-4cf5-8d40-b25c-759a9339163e'' ) ).
}] value]'); yourself)