definitions
defe6d693eaf2d41d439c6ecec536fe9ccd
	<definition>

	^ (Dictionary newFrom: {
(#block -> [:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #outer ) ).
	#out -> #(#(#automatic #'bf6db899-802f-2f43-b34d-1439eee5380a' ) #(#automatic #'61bf820b-36b7-4a42-b552-e5e4394c909a' ) ).
	#scripts -> #(#'8bf990f7-51e9-6649-8a24-aa221296e3df' #GramadaParseResultVisualizer #'067f6174-3b5d-1747-8834-2aca86ea9618' ).
	#id -> #'a0ba2335-4cf5-8d40-b25c-759a9339163e'.
	#bounds -> (1@411 corner: 735@424).
	#current -> #'8bf990f7-51e9-6649-8a24-aa221296e3df'.
}] value]).
(#class -> ViQueryStepDefinition).
(#id -> #'e6d693ea-f2d4-1d43-9c6e-cec536fe9ccd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:12:08 pm')})).
(#sourceCode -> '[:in :out | out add: {#objects -> in}, [{
	#in -> #(#(#interactive #outer ) ).
	#out -> #(#(#automatic #''bf6db899-802f-2f43-b34d-1439eee5380a'' ) #(#automatic #''61bf820b-36b7-4a42-b552-e5e4394c909a'' ) ).
	#scripts -> #(#''8bf990f7-51e9-6649-8a24-aa221296e3df'' #GramadaParseResultVisualizer #''067f6174-3b5d-1747-8834-2aca86ea9618'' ).
	#id -> #''a0ba2335-4cf5-8d40-b25c-759a9339163e''.
	#bounds -> (1@411 corner: 735@424).
	#current -> #''8bf990f7-51e9-6649-8a24-aa221296e3df''.
}] value]')})