steps
step64e3049a0face24f846da641d25c5943
	<step>

	^ ((Dictionary new) add: (#definition->#'850d592b-078a-6349-b686-52c63cde1a94'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->((Array new: 3) at: 1 put: OhmGrammar; at: 2 put: OhmRule; at: 3 put: Object; yourself)); add: (#creationTimeStamp->'1 July 2015 6:25:52 pm'); add: (#view->ViTextView); add: (#creationAuthor->'pre'); add: (#priority->30); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'6e60c028-d3e1-bf49-9c11-416b6b112930'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'64e3049a-0fac-e24f-846d-a641d25c5943'); add: (#isReference->false); yourself)