steps
step7b2e046b6047f542938be853216b364e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'7b2e046b-6047-f542-938b-e853216b364e').
(#label -> nil).
(#next -> #'6f505e41-acfd-5d4f-ada2-77cdc48e1601').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1470)}))})