steps
stepa00864aca9da7b4c856684d8a849fe5e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'ca489b64-d3e0-c343-b5e1-c28e5999d55a').
(#iconCode -> 'nil').
(#id -> #'a00864ac-a9da-7b4c-8566-84d8a849fe5e').
(#label -> nil).
(#next -> #'4e23cd6b-405e-e94f-8485-22afd117448c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1880)}))})