steps
step9735da59b580ce419647a3fd1ed024a5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'e51b5817-2aa3-0e4a-bd10-68436cd94de6').
(#iconCode -> 'nil').
(#id -> #'9735da59-b580-ce41-9647-a3fd1ed024a5').
(#label -> nil).
(#next -> #'cbc74d47-6dbd-6e47-a260-f98c9364d715').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1690)}))})