steps
stepca04a42d26a99947afa01aa1b04bfca1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'ca04a42d-26a9-9947-afa0-1aa1b04bfca1').
(#label -> nil).
(#next -> #'f88f0794-d8d8-6c4d-8b7a-445cc52f66df').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2120)}))})