steps
stepe78806f1fcd5ae41ae81896220cc4927
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #'9aa298c2-a22e-2e43-83cd-8859357e0c7a').
(#iconCode -> 'nil').
(#id -> #'e78806f1-fcd5-ae41-ae81-896220cc4927').
(#label -> nil).
(#next -> #'e68b5fc6-6c4c-504b-aaa0-628d9063c113').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1850)}))})