steps
stepee2fc82b71f1164f8178bb02c69f8ec9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'a5bc60d1-63c3-8c42-9039-698a5f637754').
(#iconCode -> 'nil').
(#id -> #'ee2fc82b-71f1-164f-8178-bb02c69f8ec9').
(#label -> nil).
(#next -> #'36a77c63-5f45-3d4f-9e19-299ea147b037').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'ee2fc82b-71f1-164f-8178-bb02c69f8ec9').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#expandAll -> true).
(#priority -> 20)}))})