steps
step86fb52a57259b645a22e32277696081e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'319d7f20-0d62-824c-8410-f435ec97d58a').
(#iconCode -> 'nil').
(#id -> #'86fb52a5-7259-b645-a22e-32277696081e').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'2ccfd452-134e-694d-b9fb-6bc3bbedcecb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:06:46 pm').
(#inputKind -> OhmDebugger)}))})