steps
stepbc5c5199b11b5a4c8363dcfb005b4abf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'a3a0aaa7-1711-094f-8621-bac1067b8ab0').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'bc5c5199-b11b-5a4c-8363-dcfb005b4abf').
(#label -> 'Senders (recursive)').
(#next -> #'0cd634b5-d35d-3a4c-8c1f-9515a57e3adb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 440)}))})