steps
step70617ea100d2104b8022828482c8d5ab
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'bdcdec5a-9ca6-404f-8de6-774c3caef595').
(#iconCode -> 'nil').
(#id -> #'70617ea1-00d2-104b-8022-828482c8d5ab').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'4db8d5db-2dd0-cd46-8f00-8add5b2abc75').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'7942fc79-4fc2-d84c-98d0-efb55e4d5ab8').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> CompiledMethod)}))})