steps
step9d8419adff55734eb7bbd038a47c312e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'6be4c0ce-5eea-be49-8207-c58ca992ee72').
(#iconCode -> 'nil').
(#id -> #'9d8419ad-ff55-734e-b7bb-d038a47c312e').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'bcc2e4a5-b885-0c4b-994d-aff86495a657').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:11:34 pm')}))})