steps
step56e04d8bf3523c4a80ba83f5bf6d6e61
	<step>

	^ ((Dictionary new) add: (#definition->#'1ea1492c-4d46-fd41-9ca6-5dda748f6e96'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'28 May 2015 10:20:48 am'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'56e04d8b-f352-3c4a-80ba-83f5bf6d6e61'); add: (#isReference->false); yourself)