steps
step5befbc74c4bae34d9e58bcf93827d5e8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'5befbc74-c4ba-e34d-9e58-bcf93827d5e8').
(#label -> nil).
(#next -> #'e9e1bde1-1735-284c-be1f-6b99473e1678').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2100)}))})