steps
stepbf465ea24035df4993e35011b872b0f6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'06ef781e-c63d-2a40-8759-cf01490b17dd').
(#iconCode -> 'nil').
(#id -> #'bf465ea2-4035-df49-93e3-5011b872b0f6').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'a42ed166-80cb-be4e-ba2a-0479156b0936').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '5 June 2015 1:26:43 pm').
(#isNew -> false)}))})