steps
stepd35e7fe288dc344291c23bf94fe89b02
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #methodReferenceToPackageName).
(#iconCode -> 'nil').
(#id -> #'d35e7fe2-88dc-3442-91c2-3bf94fe89b02').
(#label -> nil).
(#next -> #'7b2e046b-6047-f542-938b-e853216b364e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1460)}))})