steps
stepb2b4ae7898c6784491b087f17deed68c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7fbeb020-17a5-a44b-8452-d00317b036af').
(#iconCode -> 'nil').
(#id -> #'b2b4ae78-98c6-7844-91b0-87f17deed68c').
(#label -> nil).
(#next -> #'b0e115e3-6fb8-f84c-87f4-f21d46eb5c7e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:44:36 pm').
(#priority -> 4630)}))})