steps
stepa55055bd34b3384fb9da9de8d59c1343
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'d1a31df6-69aa-9f42-9638-bf514aade0ae').
(#iconCode -> 'nil').
(#id -> #'a55055bd-34b3-384f-b9da-9de8d59c1343').
(#label -> nil).
(#next -> #'b0e115e3-6fb8-f84c-87f4-f21d46eb5c7e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 3040)}))})