steps
stepohmDebuggerRuleInvocationsView
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1f2ec0d3-3b18-0640-95f7-2d52b219a8cc').
(#iconCode -> 'nil').
(#id -> #ohmDebuggerRuleInvocationsView).
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Ohm rule invocations viewer').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:09:54 pm').
(#notifier -> [ViEventNotifier named: #GramadaDebuggerStep]).
(#view -> OhmRuleInvocationsTreeView)}))})