steps
stepf0c82eea4953744b8adbbc81c119dae0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'39365f54-2259-894d-87b6-6cc0b9d8a55e').
(#iconCode -> 'nil').
(#id -> #'f0c82eea-4953-744b-8adb-bc81c119dae0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '9 June 2015 1:50:36 pm').
(#isNew -> false)}))})