steps
step8c0c7c2fde5c284d9d9a2d20961a1db5
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#iconCode -> 'nil').
(#id -> #'8c0c7c2f-de5c-284d-9d9a-2d20961a1db5').
(#label -> nil).
(#next -> #'68eda666-8d64-144e-b349-065974fd20f2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 160)}))})