steps
step57a213086be6bf4a9f88af663557c2c0
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c010479b-9a68-b243-b818-872a1180f9e5').
(#iconCode -> 'nil').
(#id -> #'57a21308-6be6-bf4a-9f88-af663557c2c0').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'3482a14e-1935-0749-8314-d5fbef0c514a').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '1 June 2015 1:30:44 pm').
(#isNew -> false)}))})