steps
stepd11255808a80594fa31e9a41d7c710a3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c19dea0f-4ac7-0443-b995-4863e9209dcb').
(#iconCode -> 'nil').
(#id -> #'d1125580-8a80-594f-a31e-9a41d7c710a3').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'64077c63-d342-6c4b-a20c-90b0865cfdb6').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:12:36 pm').
(#priority -> 1).
(#view -> ViTreeViewExtended)}))})