steps
step6494b43072e54a44b03e56da9dcd8e3d
	<step>

	^ ((Dictionary new) add: (#definition->#'eeba6bcc-2968-e44f-9a88-2b2a25cbfd03'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#view->ViTextView); add: (#creationTimeStamp->'27 May 2015 6:11:15 pm'); add: (#notifier->[ViEventNotifier named: #GramadaDebuggerStep]); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'9d8419ad-ff55-734e-b7bb-d038a47c312e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'6494b430-72e5-4a44-b03e-56da9dcd8e3d'); add: (#isReference->false); yourself)