steps
step265f5360f208fe42b68ae42b58b5ff93
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'265f5360-f208-fe42-b68a-e42b58b5ff93').
(#label -> nil).
(#next -> #'38cdc208-e708-0b47-b9d5-d9fb2a99fce1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Methods').
(#priority -> 1910)}))})