steps
stepce6ad922f4f3a043ba74a843f21c5238
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a7588d6d-3cb7-2d4e-afc0-18634b878317').
(#iconCode -> 'nil').
(#id -> #'ce6ad922-f4f3-a043-ba74-a843f21c5238').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Copy of Grammars').
(#next -> #'c26af066-17fd-4448-9829-5f6396db27e7').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #ohmSystemGrammars).
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:46 am').
(#isNew -> false).
(#notifier -> OhmViChangeNotifier)}))})