steps
stepb675a2adabbe43499091add2414ff6b3
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'65fe476b-3cd6-9948-8d49-ec4ec931d81c').
(#iconCode -> 'nil').
(#id -> #'b675a2ad-abbe-4349-9091-add2414ff6b3').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'2e1557ac-163f-6747-b6e3-fb9fa973de62').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'b675a2ad-abbe-4349-9091-add2414ff6b3').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#notifier -> [ViEventNotifier named: #GramadaSyntaxTestsExecuted]).
(#view -> ViPluggableTreeMorph)}))})