steps
step4a5e36f99a70394aa39bc0891bc2e99b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'81d4bba3-fa92-5a44-9759-d980ccef208a').
(#iconCode -> 'nil').
(#id -> #'4a5e36f9-9a70-394a-a39b-c0891bc2e99b').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Protocol').
(#labelColor -> '#AAAAAA').
(#priority -> 1870)}))})