steps
step648936db9a22ed48a05e4f1c8c9c94fd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'308ec58a-07f8-bc41-91de-d5f7e6f778ae').
(#iconCode -> 'nil').
(#id -> #'648936db-9a22-ed48-a05e-4f1c8c9c94fd').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2700)}))})