steps
step97ad3fc76ae68145a2794414ebdd6804
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #toplevelClasses).
(#iconCode -> 'nil').
(#id -> #'97ad3fc7-6ae6-8145-a279-4414ebdd6804').
(#label -> nil).
(#next -> #'19536a17-53f2-a544-90d1-73c5acc3cb61').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2050)}))})