steps
step6049746d7182cc42972df77ab0baefca
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'6a9db3f0-20ae-d541-bded-40c32e0a065a').
(#iconCode -> 'nil').
(#id -> #'6049746d-7182-cc42-972d-f77ab0baefca').
(#label -> nil).
(#next -> #'a55055bd-34b3-384f-b9da-9de8d59c1343').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Code').
(#labelColor -> '#AAAAAA').
(#priority -> 3030)}))})