steps
stepeac8722e840ed245906beb6a01ac58a1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'718de269-27aa-d24a-9303-013c573b12ba').
(#iconCode -> 'UiFugueIcons priceTagIcon').
(#id -> #'eac8722e-840e-d245-906b-eb6a01ac58a1').
(#label -> 'Protocols (objectified)').
(#next -> #'959bb1be-7400-8b46-bbf7-ad6fc02146e4').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 110)}))})