steps
step746c8ffb51dea64c8988517485778a87
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'07161242-230e-1049-93b7-2f75e3deef7b').
(#iconCode -> 'nil').
(#id -> #'746c8ffb-51de-a64c-8988-517485778a87').
(#label -> nil).
(#next -> #'e78806f1-fcd5-ae41-ae81-896220cc4927').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1840)}))})