steps
stepe68b5fc66c4c504baaa0628d9063c113
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #iconAndLabel).
(#iconCode -> 'nil').
(#id -> #'e68b5fc6-6c4c-504b-aaa0-628d9063c113').
(#label -> nil).
(#next -> #'4a5e36f9-9a70-394a-a39b-c0891bc2e99b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Methods').
(#priority -> 1860)}))})