steps
stepb0e115e36fb8f84c87f4f21d46eb5c7e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'9f165395-722b-6b41-979e-695440a8254b').
(#iconCode -> 'UiFugueIcons documentNodeIcon').
(#id -> #'b0e115e3-6fb8-f84c-87f4-f21d46eb5c7e').
(#label -> 'Abstract Syntax Tree').
(#next -> #'6c0a1727-d1af-3a4a-a6b8-79445faf91a2').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Type').
(#priority -> 3010)}))})