steps
stepdb04b0b5eb1f8945b4dbda79d40af71a
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'78d57678-18df-ed4f-8b2b-d2b9bd33ecdc').
(#iconCode -> 'nil').
(#id -> #'db04b0b5-eb1f-8945-b4db-da79d40af71a').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Node result on string').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:26:30 pm').
(#inputKind -> OhmNode).
(#isNew -> false).
(#priority -> 5).
(#view -> OhmViNodeStringView)}))})