steps
stepe80d4dc3ffec204d8587d4bb97880132
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'bd42b84b-e2e0-3f44-9361-626b76d2721f').
(#iconCode -> 'nil').
(#id -> #'e80d4dc3-ffec-204d-8587-d4bb97880132').
(#label -> nil).
(#next -> #'69e4b48a-26f2-2947-920e-1ddf9f97ad0e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:07:16 pm').
(#priority -> 4950)}))})