steps
step6e60c028d3e1bf499c11416b6b112930
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'743cc13c-6011-804c-9b96-1261e7ecdef2').
(#iconCode -> 'nil').
(#id -> #'6e60c028-d3e1-bf49-9c11-416b6b112930').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '1 July 2015 6:28:27 pm').
(#inputKind -> Object)}))})