steps
steped426c8eaf11614e83894c0d36c6c86b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'ed426c8e-af11-614e-8389-4c0d36c6c86b').
(#label -> nil).
(#next -> #'07540f0c-6cda-d44e-b272-9d619e7cdcff').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2240)}))})