steps
stepa405ca756b83f64d85a7334f3151cfcf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33').
(#iconCode -> 'nil').
(#id -> #'a405ca75-6b83-f64d-85a7-334f3151cfcf').
(#label -> 'Classes').
(#next -> #'5cb7a38d-cab6-d44e-b38f-779f66faf736').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 5630)}))})