steps
step4db8d5db2dd0cd468f008add5b2abc75
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'598085a9-4bef-3e4a-ac08-6a6a2018be60').
(#iconCode -> 'nil').
(#id -> #'4db8d5db-2dd0-cd46-8f00-8add5b2abc75').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'99b5946f-c38d-e94f-919d-5923f81b148a').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> Object)}))})