steps
step9f6bdb1099c00845806fe60405d4bebd
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'9f6bdb10-99c0-0845-806f-e60405d4bebd').
(#label -> nil).
(#next -> #'9735da59-b580-ce41-9647-a3fd1ed024a5').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1680)}))})