steps
step4c25e30468cbd3499eea97514506a5aa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'3994d384-d109-e44e-8b92-9a64780ce685').
(#iconCode -> 'nil').
(#id -> #'4c25e304-68cb-d349-9eea-97514506a5aa').
(#label -> nil).
(#next -> #'eb2eeadd-07f1-b046-a798-7eeff5e3eeda').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:06:28 pm').
(#priority -> 4970)}))})