steps
step4fc198280194f04685e2a6f160b52f5b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'94349485-e72e-6d47-b370-a6a240d8da9f').
(#iconCode -> 'UiSilkIcons lightningDeleteIcon').
(#id -> #'4fc19828-0194-f046-85e2-a6f160b52f5b').
(#label -> 'Reject Errors').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4570)}))})