steps
stepeb2eeadd07f1b046a7987eeff5e3eeda
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'24bf9bee-2765-9c47-bee3-07990a61c4a5').
(#iconCode -> 'nil').
(#id -> #'eb2eeadd-07f1-b046-a798-7eeff5e3eeda').
(#label -> nil).
(#next -> #'c6559236-7b06-9748-a18d-09f2ae6515f8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '3 February 2014 5:08:07 pm').
(#priority -> 4980)}))})