steps
step067f61743b5d174788342aca86ea9618
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9709bb2d-dd48-574a-8b2d-525ecb72d8c8').
(#iconCode -> 'nil').
(#id -> #'067f6174-3b5d-1747-8834-2aca86ea9618').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 4:35:44 pm')}))})