steps
stepe564be1431e96b428689902f00c63ece
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'80ccb737-55a3-6440-b360-f02ac53f3684').
(#iconCode -> 'nil').
(#id -> #'e564be14-31e9-6b42-8689-902f00c63ece').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'4025ef34-392e-a14d-adf1-248a64aeb59e').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#view -> ViMultiPaneTiled)}))})