steps
stepformattedQueries
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'7e9d16d4-7549-f441-bf3d-74fbe6115750').
(#iconCode -> 'nil').
(#id -> #formattedQueries).
(#label -> 'Formatted Queries').
(#next -> #'6add0b0f-920d-894b-8c60-7e275fc7080f').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6060)}))})