steps
step5cb7a38dcab6d44eb38f779f66faf736
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'058d3529-d310-e847-b148-dadf47ff31b9').
(#iconCode -> 'nil').
(#id -> #'5cb7a38d-cab6-d44e-b38f-779f66faf736').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '19 February 2014 4:06:47 pm').
(#priority -> 5910)}))})