steps
step6494b43072e54a44b03e56da9dcd8e3d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'eeba6bcc-2968-e44f-9a88-2b2a25cbfd03').
(#iconCode -> 'nil').
(#id -> #'6494b430-72e5-4a44-b03e-56da9dcd8e3d').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'9d8419ad-ff55-734e-b7bb-d038a47c312e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:11:15 pm').
(#notifier -> [ViEventNotifier named: #GramadaDebuggerStep]).
(#view -> ViTextView)}))})