steps
stepea584df045b35e419a9ee9b53c1a0598
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#iconCode -> 'nil').
(#id -> #'ea584df0-45b3-5e41-9a9e-e9b53c1a0598').
(#label -> nil).
(#next -> #'d21cc716-3ab1-1243-b995-da9e0813fa99').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '20 February 2014 1:44:22 pm').
(#priority -> 5700)}))})