steps
stepd21cc7163ab11243b995da9e0813fa99
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'d21cc716-3ab1-1243-b995-da9e0813fa99').
(#label -> nil).
(#next -> #'72a1887e-14c8-bb4b-8816-c1a83b525e41').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 190)}))})