steps
step045aec6e9a856c4f93a4568eebb6305d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'fddec992-34bd-3947-b1b5-8c1c943b03af').
(#iconCode -> 'nil').
(#id -> #'045aec6e-9a85-6c4f-93a4-568eebb6305d').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 November 2017 9:34:46 am')}))})