steps
step6984c6e097664d45852038f66da3cd32
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8d8c0677-fb62-2547-b0ca-9397bf9ffce5').
(#iconCode -> 'nil').
(#id -> #'6984c6e0-9766-4d45-8520-38f66da3cd32').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1770)}))})