steps
stepcd563aef8bdc1746b41480fad70add58
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'93525b3f-5fde-bb4c-ad94-1c2c3a53fd53').
(#iconCode -> 'nil').
(#id -> #'cd563aef-8bdc-1746-b414-80fad70add58').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '5 May 2014 2:26:38 pm').
(#priority -> 6070)}))})