steps
step6c0a1727d1af3a4aa6b879445faf91a2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'eb0e6538-06eb-e34e-8e20-8914317b1981').
(#iconCode -> 'nil').
(#id -> #'6c0a1727-d1af-3a4a-a6b8-79445faf91a2').
(#label -> nil).
(#next -> #'6049746d-7182-cc42-972d-f77ab0baefca').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Token').
(#labelColor -> '#AAAAAA').
(#priority -> 3020)}))})