steps
step64e3049a0face24f846da641d25c5943
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'850d592b-078a-6349-b686-52c63cde1a94').
(#iconCode -> 'nil').
(#id -> #'64e3049a-0fac-e24f-846d-a641d25c5943').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'6e60c028-d3e1-bf49-9c11-416b6b112930').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '1 July 2015 6:25:52 pm').
(#inputKind -> {OhmGrammar. OhmRule. Object}).
(#priority -> 30).
(#view -> ViTextView)}))})