steps
step7422d4b077d42d43b1a27c93516983f7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'73e83736-5144-8f47-ba71-3ddb8ee006e5').
(#iconCode -> 'nil').
(#id -> #'7422d4b0-77d4-2d43-b1a2-7c93516983f7').
(#label -> 'All subclasses').
(#next -> #'5befbc74-c4ba-e34d-9e58-bcf93827d5e8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 300)}))})