steps
step63749d6ed32b814e8bc78d3f7f291949
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'63749d6e-d32b-814e-8bc7-8d3f7f291949').
(#label -> nil).
(#next -> #'746c8ffb-51de-a64c-8988-517485778a87').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1830)}))})