steps
step47c0f87b073af54bb1b49a8238a4b7b9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'f1e39058-8fc6-ea47-a516-6eedee86a1eb').
(#iconCode -> 'nil').
(#id -> #'47c0f87b-073a-f54b-b1b4-9a8238a4b7b9').
(#label -> 'Methods (full)').
(#next -> #'63749d6e-d32b-814e-8bc7-8d3f7f291949').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 250)}))})