steps
stepGramadaParseResultVisualizer
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1db6c178-bad4-514a-b5da-0e18e7b312e9').
(#iconCode -> 'nil').
(#id -> #GramadaParseResultVisualizer).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Parse Result Visualizer').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'db04b0b5-eb1f-8945-b4db-da79d40af71a').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:27:12 pm').
(#inputKind -> OhmMatchResult).
(#priority -> 6).
(#view -> OhmViNodeStringView)}))})