steps
step1bccd2506819924d9c65aecfa8e24162
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b61bd1f2-25a2-1745-b8fa-8c088492c1d8').
(#iconCode -> 'nil').
(#id -> #'1bccd250-6819-924d-9c65-aecfa8e24162').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'b03a5781-aedc-5c47-a02b-4432d5809e94').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:20:05 am').
(#view -> ViTextEdit)}))})