steps
step36a77c635f453d4f9e19299ea147b037
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'16098bad-c8bf-434e-a06d-18cd2a87edf8').
(#iconCode -> 'UiSilkIcons carIcon').
(#id -> #'36a77c63-5f45-3d4f-9e19-299ea147b037').
(#label -> 'Class hierarchy').
(#next -> #'9f6bdb10-99c0-0845-806f-e60405d4bebd').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1670)}))})