steps
step2ccfd452134e694db9fb6bc3bbedcecb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b470ebdb-97b5-0749-9ce2-7cc8601ff30e').
(#iconCode -> 'nil').
(#id -> #'2ccfd452-134e-694d-b9fb-6bc3bbedcecb').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:08:46 pm').
(#inputKind -> OhmDebugger)}))})