steps
step2ccfd452134e694db9fb6bc3bbedcecb
	<step>

	^ ((Dictionary new) add: (#definition->#'b470ebdb-97b5-0749-9ce2-7cc8601ff30e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->OhmDebugger); add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'27 May 2015 6:08:46 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'2ccfd452-134e-694d-b9fb-6bc3bbedcecb'); add: (#isReference->false); yourself)