steps
stepohmSystemGrammars
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'3c11ba44-1272-9d42-b500-8223548c977e').
(#iconCode -> 'nil').
(#id -> #ohmSystemGrammars).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Grammars').
(#next -> #'65993183-1d44-6440-9ff3-b525244b1359').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 5:33:44 pm').
(#isNew -> false).
(#notifier -> OhmViChangeNotifier)}))})