steps
step6add0b0f920d894b8c607e275fc7080f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'8ad783be-1900-e64d-8e3c-ec7881484f24').
(#iconCode -> 'nil').
(#id -> #'6add0b0f-920d-894b-8c60-7e275fc7080f').
(#label -> nil).
(#next -> #'cd563aef-8bdc-1746-b414-80fad70add58').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 December 2014 10:17:08 am')}))})