steps
step4e06ed51665de446a53c44763032a14c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #methodReferenceToPackageName).
(#iconCode -> 'nil').
(#id -> #'4e06ed51-665d-e446-a53c-44763032a14c').
(#label -> nil).
(#next -> #'ed426c8e-af11-614e-8389-4c0d36c6c86b').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2230)}))})