steps
step0cd634b5d35d3a4c8c1f9515a57e3adb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsBySelector).
(#iconCode -> 'nil').
(#id -> #'0cd634b5-d35d-3a4c-8c1f-9515a57e3adb').
(#label -> nil).
(#next -> #'d35e7fe2-88dc-3442-91c2-3bf94fe89b02').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1450)}))})