steps
stepcf71b2a8b067cf4ab4f8b4e1d5857c61
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1cfcb90a-ec5e-7e48-b153-1ea3ce6c1baf').
(#iconCode -> 'nil').
(#id -> #'cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Copy of Copy of Identity').
(#next -> #'7be3dc6e-cfdf-ef44-beb3-c6e52270e97f').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'cf71b2a8-b067-cf4a-b4f8-b4e1d5857c61').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#priority -> 60).
(#view -> ViButtonBarView)}))})