steps
stepec27e35b91eeb94e9342baa884132c3d
	<step>

	^ ((Dictionary new) add: (#definition->#'8bbd1ad2-f7ff-344d-b98b-69f4cf799e1c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->OhmRule); add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'18 November 2015 4:05:02 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ec27e35b-91ee-b94e-9342-baa884132c3d'); add: (#isReference->false); yourself)