steps
step659931831d4464409ff3b525244b1359
	<step>

	^ ((Dictionary new) add: (#definition->#'38368f17-f259-ea4f-a77c-fe3f65f460fe'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'27 May 2015 5:33:51 pm'); yourself)); add: (#isProperty->true); add: (#next->#'cb27335f-db56-7846-b984-df3362a4ee99'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'65993183-1d44-6440-9ff3-b525244b1359'); add: (#isReference->false); yourself)