steps
stepcb27335fdb567846b984df3362a4ee99
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'87d98209-5c78-e94c-b85c-fcf13dc9e3d2').
(#iconCode -> 'nil').
(#id -> #'cb27335f-db56-7846-b984-df3362a4ee99').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '4 June 2015 2:23:27 pm').
(#isNew -> false)}))})