steps
stepce0a75229f8ccb419347ca73d724631d
	<step>

	^ ((Dictionary new) add: (#definition->#'9bce5100-007e-7d43-afd2-3d20862ff9a9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#view->ViMultiPaneTiled); add: (#creationTimeStamp->'27 May 2015 6:10:35 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'06d981e6-68e4-8b48-9c64-baf8dff56bc2'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ce0a7522-9f8c-cb41-9347-ca73d724631d'); add: (#isReference->false); yourself)