steps
step10e888accb08ce4380f520c8b8df0784
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0cd7a59e-6eb3-4a43-ad0b-84763496cf7f').
(#iconCode -> 'nil').
(#id -> #'10e888ac-cb08-ce43-80f5-20c8b8df0784').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'4d7f8e26-743a-bd4e-b827-9cefcda29555').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '9 June 2015 10:08:47 am').
(#isNew -> false)}))})