steps
step56e04d8bf3523c4a80ba83f5bf6d6e61
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'1ea1492c-4d46-fd41-9ca6-5dda748f6e96').
(#iconCode -> 'nil').
(#id -> #'56e04d8b-f352-3c4a-80ba-83f5bf6d6e61').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:20:48 am').
(#view -> ViMultiPaneTiled)}))})