steps
step5326b58ad326ad4996267de82d0b49cb
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'9100cc23-b8b1-fa48-a4ac-86f413bfff4b').
(#iconCode -> 'nil').
(#id -> #'5326b58a-d326-ad49-9626-7de82d0b49cb').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'31c9d76a-803e-8144-b51e-33d999326cee').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:48 am').
(#view -> ViMultiPaneTiled)}))})