steps
step72a1887e14c8bb4b8816c1a83b525e41
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'c3876e02-15ba-414a-ae61-c41de8ba4e72').
(#iconCode -> 'UiFugueIcons scriptsTextIcon').
(#id -> #'72a1887e-14c8-bb4b-8816-c1a83b525e41').
(#label -> 'Implementors (recursive)').
(#next -> #'4e06ed51-665d-e446-a53c-44763032a14c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 340)}))})