steps
stepb03a5781aedc5c47a02b4432d5809e94
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'4e0ea172-e845-3841-a96b-8de7c54af59a').
(#iconCode -> 'nil').
(#id -> #'b03a5781-aedc-5c47-a02b-4432d5809e94').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#autoAccept -> true).
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:35:30 am')}))})