steps
stepGramadaGrammarRuleBrowser
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'bf0699a9-4caa-9f4b-aa48-a7e1807e070e').
(#iconCode -> 'nil').
(#id -> #GramadaGrammarRuleBrowser).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Ohm Rules').
(#next -> #'ec27e35b-91ee-b94e-9342-baa884132c3d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '18 November 2015 4:04:26 pm').
(#inputKind -> OhmGrammar).
(#notifier -> OhmViChangeNotifier).
(#priority -> 1)}))})