steps
step659bb790ed7e4a4493d4298862236d0b
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'659bb790-ed7e-4a44-93d4-298862236d0b').
(#label -> nil).
(#next -> #'1d5de9cf-9877-a848-91b4-9715373f1ad1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:51:45 pm').
(#priority -> 4660)}))})