steps
stepbee7ccaa7d429641b8d578a0c4f7224d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#iconCode -> 'nil').
(#id -> #'bee7ccaa-7d42-9641-b8d5-78a0c4f7224d').
(#label -> nil).
(#next -> #'c753d700-0c1c-024c-a7d1-68ffe3bc4166').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '23 July 2014 12:56:18 pm').
(#priority -> 6580)}))})