steps
stepsnippets
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'46e862b1-69aa-e348-ac02-6f21384543b3').
(#iconCode -> 'nil').
(#id -> #snippets).
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'5e29ea34-ab1f-4c40-9122-36f7572fc535').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 June 2015 5:17:29 pm').
(#inputKind -> Object).
(#isNew -> false).
(#outputKind -> ViQueryStepDefinition).
(#view -> ViTreeViewExtended)}))})