steps
step0d87f2242efe7b449e62ddef7dfe44b9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#iconCode -> 'nil').
(#id -> #'0d87f224-2efe-7b44-9e62-ddef7dfe44b9').
(#label -> nil).
(#next -> #'6d7f9bea-0e5c-c94c-a4cb-7c20ea715fa8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 170)}))})