steps
stepbfba48f1fd28f949af2f0335e57e78cc
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #identity).
(#iconCode -> 'UiFugueIcons nodeIcon').
(#id -> #'bfba48f1-fd28-f949-af2f-0335e57e78cc').
(#label -> 'Class hierarchy (full)').
(#next -> #'5866e81b-ba19-1a42-bcba-6b513172dc16').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 290)}))})