steps
step5866e81bba191a42bcba6b513172dc16
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #compareObjectsByName).
(#iconCode -> 'nil').
(#id -> #'5866e81b-ba19-1a42-bcba-6b513172dc16').
(#label -> nil).
(#next -> #'97ad3fc7-6ae6-8145-a279-4414ebdd6804').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2040)}))})