steps
step5e4653088af57b4f9372db5466573429
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0d217a0c-cb9a-2b4a-9d29-95b0ed8db3b6').
(#iconCode -> 'nil').
(#id -> #'5e465308-8af5-7b4f-9372-db5466573429').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'10e888ac-cb08-ce43-80f5-20c8b8df0784').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '9 June 2015 10:03:23 am').
(#isNew -> false)}))})