steps
stepf657b277fa4dd346b18c6ff6ffe558fa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'05e20c00-19c2-b546-be31-ae5d98b374f1').
(#iconCode -> 'nil').
(#id -> #'f657b277-fa4d-d346-b18c-6ff6ffe558fa').
(#label -> 'Code').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6170)}))})