steps
step71dfa65f9c442a418cf308ac2c9154d8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'9d5a860e-218e-3f48-b99c-c85e33aa4e5f').
(#iconCode -> 'nil').
(#id -> #'71dfa65f-9c44-2a41-8cf3-08ac2c9154d8').
(#label -> nil).
(#next -> #'f45253e3-1e61-2344-8ebb-69fad9e592af').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1710)}))})