steps
stepdd197842f4184e4fa3050fdfc97e60d6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'42833415-c0c1-5547-a2d4-2379c3d211c3').
(#iconCode -> 'UiFugueIcons blockIcon').
(#id -> #'dd197842-f418-4e4f-a305-0fdfc97e60d6').
(#label -> 'Instance variables').
(#next -> #'4b707439-66b1-c64b-805a-80c63759305e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 790)}))})