steps
stepbcc2e4a5b8850c4b994daff86495a657
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'48da8a27-387c-0f46-81a9-61696fe5cfaa').
(#iconCode -> 'nil').
(#id -> #'bcc2e4a5-b885-0c4b-994d-aff86495a657').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:11:54 pm')}))})