steps
step5e29ea34ab1f4c40912236f7572fc535
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'f08f246c-85f1-3d49-90d6-0dd64af2c127').
(#iconCode -> 'nil').
(#id -> #'5e29ea34-ab1f-4c40-9122-36f7572fc535').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '8 June 2015 6:08:58 pm').
(#inputKind -> ViQueryStepDefinition).
(#isNew -> false)}))})