steps
step31f89720da42cf44b43e1de2fca6bfa1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'7f5468a3-1dc7-1340-9212-4ad1ee77effc').
(#iconCode -> 'nil').
(#id -> #'31f89720-da42-cf44-b43e-1de2fca6bfa1').
(#label -> 'Layout Properties').
(#next -> #'e80d4dc3-ffec-204d-8587-d4bb97880132').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #defaultProperties).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 600)}))})