steps
step38cdc208e7080b47b9d5d9fb2a99fce1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'81d4bba3-fa92-5a44-9759-d980ccef208a').
(#iconCode -> 'nil').
(#id -> #'38cdc208-e708-0b47-b9d5-d9fb2a99fce1').
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#headerText -> 'Protocol').
(#labelColor -> '#AAAAAA').
(#priority -> 1920)}))})