steps
stepe9e1bde11735284cbe1f6b99473e1678
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #category).
(#iconCode -> 'nil').
(#id -> #'e9e1bde1-1735-284c-be1f-6b99473e1678').
(#label -> nil).
(#next -> #'ca04a42d-26a9-9947-afa0-1aa1b04bfca1').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2110)}))})