steps
stepGramadaGrammarsBrowser
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'0f4f6049-6ad8-704b-a60c-403d34757c95').
(#iconCode -> 'nil').
(#id -> #GramadaGrammarsBrowser).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Grammars').
(#next -> #'bf465ea2-4035-df49-93e3-5011b872b0f6').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'1d988069-7a09-0742-bb77-0dbb7448bf82').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '5 June 2015 1:26:43 pm').
(#isNew -> false).
(#notifier -> OhmViChangeNotifier)}))})