steps
stepf88f0794d8d86c4d8b7a445cc52f66df
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #toplevelClasses).
(#iconCode -> 'nil').
(#id -> #'f88f0794-d8d8-6c4d-8b7a-445cc52f66df').
(#label -> nil).
(#next -> #'962950ed-4ad4-244b-9e1b-512547f2422f').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 2130)}))})