steps
step06d981e668e48b489c64baf8dff56bc2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'e6d693ea-f2d4-1d43-9c6e-cec536fe9ccd').
(#iconCode -> 'nil').
(#id -> #'06d981e6-68e4-8b48-9c64-baf8dff56bc2').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'f15ca946-a8a8-1d40-933d-d7eb0d239d25').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:12:08 pm').
(#view -> ViMultiPaneTiled)}))})