steps
stepcbc74d476dbd6e47a260f98c9364d715
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupSortStep).
(#definition -> #compareObjectsAsStrings).
(#iconCode -> 'nil').
(#id -> #'cbc74d47-6dbd-6e47-a260-f98c9364d715').
(#label -> nil).
(#next -> #'71dfa65f-9c44-2a41-8cf3-08ac2c9154d8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1700)}))})