steps
step9727e8f33a467549adebb57ccead9114
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'9727e8f3-3a46-7549-adeb-b57ccead9114').
(#label -> nil).
(#next -> #implementors).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 180)}))})