steps
step69e4b48a26f22947920e1ddf9f97ad0e
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'0ef356e7-2ba9-9e49-a899-6f24e6c8fda2').
(#iconCode -> 'nil').
(#id -> #'69e4b48a-26f2-2947-920e-1ddf9f97ad0e').
(#label -> nil).
(#next -> #'4c25e304-68cb-d349-9eea-97514506a5aa').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'d9634b11-bde6-1a40-a0b4-7be880afc37a').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 4960)}))})