steps
step64077c63d3426c4ba20c90b0865cfdb6
	<step>

	^ ((Dictionary new) add: (#definition->#'e2611fa5-0fe1-b549-b9ef-6bc73efae46b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'9 June 2015 9:55:33 am'); yourself)); add: (#isProperty->false); add: (#next->#'874543ca-2621-a14d-bb0e-8a0a48b49afa'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'64077c63-d342-6c4b-a20c-90b0865cfdb6'); add: (#isReference->false); yourself)