steps
stepf15ca946a8a81d40933dd7eb0d239d25
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'652273fd-6596-5b44-bfe1-431c6aa636e1').
(#iconCode -> 'nil').
(#id -> #'f15ca946-a8a8-1d40-933d-d7eb0d239d25').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:12:58 pm').
(#view -> ViMultiPaneTiled)}))})