steps
step981d1d35ca7ad842824cb8c0e09bce59
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'98194b7c-fcf9-4744-ae4d-94665e508f49').
(#iconCode -> 'nil').
(#id -> #'981d1d35-ca7a-d842-824c-b8c0e09bce59').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'70617ea1-00d2-104b-8022-828482c8d5ab').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'a35d5181-41e0-ee4e-9909-049d68a5ae5b').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> CompiledMethod)}))})