steps
stepdc8a3ba9b6560e4fae7727779ca5efaf
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8c65f0c3-8502-9e4a-af74-3c5cb5066fd6').
(#iconCode -> 'nil').
(#id -> #'dc8a3ba9-b656-0e4f-ae77-27779ca5efaf').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'57a21308-6be6-bf4a-9f88-af663557c2c0').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'1f06d09d-dfa3-cd47-af0f-cfae2e850ae5').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '1 June 2015 1:30:44 pm').
(#isNew -> false)}))})