steps
stepGramadaGrammarLiveEditor
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'362ab341-ab1e-4a4c-9c01-14acc2ed3e86').
(#iconCode -> 'nil').
(#id -> #GramadaGrammarLiveEditor).
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Live Editor').
(#next -> #'5326b58a-d326-ad49-9626-7de82d0b49cb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:46 am').
(#fixedLayout -> true).
(#optimalExtent -> (391@422)).
(#view -> ViMultiPaneTiled)}))})