steps
stepce6ad922f4f3a043ba74a843f21c5238
	<step>

	^ ((Dictionary new) add: (#definition->#'a7588d6d-3cb7-2d4e-afc0-18634b878317'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#notifier->OhmViChangeNotifier); add: (#copyOf->#ohmSystemGrammars); add: (#creationTimeStamp->'28 May 2015 10:19:46 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'c26af066-17fd-4448-9829-5f6396db27e7'); add: (#label->'Copy of Grammars'); add: (#iconCode->'nil'); add: (#id->#'ce6ad922-f4f3-a043-ba74-a843f21c5238'); add: (#isReference->false); yourself)