steps
stepb01c399de950454798343408caa906ac
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'7057516c-b98e-ea4a-8d54-c4c3a0f4ab33').
(#iconCode -> 'nil').
(#id -> #'b01c399d-e950-4547-9834-3408caa906ac').
(#label -> nil).
(#next -> #'36a77c63-5f45-3d4f-9e19-299ea147b037').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 230)}))})