steps
step6e60c028d3e1bf499c11416b6b112930
	<step>

	^ ((Dictionary new) add: (#definition->#'743cc13c-6011-804c-9b96-1261e7ecdef2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Object); add: (#creationTimeStamp->'1 July 2015 6:28:27 pm'); add: (#creationAuthor->'pre'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'6e60c028-d3e1-bf49-9c11-416b6b112930'); add: (#isReference->false); yourself)