steps
step7be3dc6ecfdfef44beb3c6e52270e97f
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'b1f3a8df-6782-6b4c-be1e-6e069e9e2d19').
(#iconCode -> 'nil').
(#id -> #'7be3dc6e-cfdf-ef44-beb3-c6e52270e97f').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'bf69c12e-fa26-224b-b22f-8e4fc1a62547').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> TestCase class)}))})