steps
stepcb27335fdb567846b984df3362a4ee99
	<step>

	^ ((Dictionary new) add: (#definition->#'87d98209-5c78-e94c-b85c-fcf13dc9e3d2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'4 June 2015 2:23:27 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'cb27335f-db56-7846-b984-df3362a4ee99'); add: (#isReference->false); yourself)