steps
stepGramadaSyntaxTestBrowser
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'804d1524-a739-1b46-808a-044f2c24b914').
(#iconCode -> 'nil').
(#id -> #GramadaSyntaxTestBrowser).
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Syntax Test Browser').
(#next -> #'e564be14-31e9-6b42-8689-902f00c63ece').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'513d503f-db81-a44b-85cb-b563c82c7421').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#optimalExtent -> (365@411)).
(#view -> ViMultiPaneTiled)}))})