steps
stepGramadaParseResultVisualizer
	<step>

	^ ((Dictionary new) add: (#definition->#'1db6c178-bad4-514a-b5da-0e18e7b312e9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->OhmNode); add: (#creationTimeStamp->'27 May 2015 6:27:12 pm'); add: (#priority->5); add: (#creationAuthor->'pre'); add: (#view->OhmViNodeStringView); add: (#copyOf->#'db04b0b5-eb1f-8945-b4db-da79d40af71a'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Parse Result Visualizer'); add: (#iconCode->'nil'); add: (#id->#GramadaParseResultVisualizer); add: (#isReference->false); yourself)