steps
step2e1557ac163f6747b6e3fb9fa973de62
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'d1e0ad0a-5a30-cf4d-9b29-db07dd6cd108').
(#iconCode -> 'nil').
(#id -> #'2e1557ac-163f-6747-b6e3-fb9fa973de62').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'0d13b248-416e-c04b-a5b7-c1ea78d951f6').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'6dbf5ed5-967c-9546-9a83-601c286c95c6').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> TestCase class)}))})