steps
stepf2dffe4f0120a8419ac3bf7dcdaa147d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'7f12b533-5efe-5343-a0eb-54d991cff7a4').
(#iconCode -> 'nil').
(#id -> #'f2dffe4f-0120-a841-9ac3-bf7dcdaa147d').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'045aec6e-9a85-6c4f-93a4-568eebb6305d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 November 2017 9:35:21 am')}))})