steps
step728402d7f870e7438d2aabf2353efba1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #removeDuplicates).
(#iconCode -> 'nil').
(#id -> #'728402d7-f870-e743-8d2a-abf2353efba1').
(#label -> 'Identity w/o duplicates').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 620)}))})