steps
stepb120830fe164624d9b168fc33fab0e43
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'37b396f7-407c-3b4d-a914-f5d2034918ca').
(#iconCode -> 'UiFugueIcons priceTagIcon').
(#id -> #'b120830f-e164-624d-9b16-8fc33fab0e43').
(#label -> 'Protocols').
(#next -> #'f55a7838-28be-ae4d-829c-e8132ee78d9e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 120)}))})