steps
step4e23cd6b405ee94f848522afd117448c
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryGroupStep).
(#definition -> #'07161242-230e-1049-93b7-2f75e3deef7b').
(#iconCode -> 'nil').
(#id -> #'4e23cd6b-405e-e94f-8485-22afd117448c').
(#label -> nil).
(#next -> #'8e40f69c-6657-8340-838b-dd4fb3a4e0b8').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1890)}))})