steps
stepc753d7000c1c024ca7d168ffe3bc4166
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryPropertyStep).
(#definition -> #'cfeaece5-e6ec-3a44-9e8b-e84b31e5ed0e').
(#iconCode -> 'nil').
(#id -> #'c753d700-0c1c-024c-a7d1-68ffe3bc4166').
(#label -> 'Code').
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6150)}))})