steps
step874543ca2621a14dbb0e8a0a48b49afa
	<step>

	^ ((Dictionary new) add: (#definition->#'284bed53-cf55-e943-9f0d-2c9aa782b9d7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#isNew->false); add: (#creationTimeStamp->'9 June 2015 10:03:06 am'); yourself)); add: (#isProperty->false); add: (#next->#'5e465308-8af5-7b4f-9372-db5466573429'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'874543ca-2621-a14d-bb0e-8a0a48b49afa'); add: (#isReference->false); yourself)