steps
step57a213086be6bf4a9f88af663557c2c0
	<step>

	^ ((Dictionary new) add: (#definition->#'c010479b-9a68-b243-b818-872a1180f9e5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#creationTimeStamp->'1 June 2015 1:30:44 pm'); add: (#copyOf->#'3482a14e-1935-0749-8314-d5fbef0c514a'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'57a21308-6be6-bf4a-9f88-af663557c2c0'); add: (#isReference->false); yourself)