steps
step68eda6668d64144eb349065974fd20f2
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'68eda666-8d64-144e-b349-065974fd20f2').
(#label -> nil).
(#next -> #senders).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:49:11 pm').
(#priority -> 4640)}))})