steps
step874543ca2621a14dbb0e8a0a48b49afa
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'284bed53-cf55-e943-9f0d-2c9aa782b9d7').
(#iconCode -> 'nil').
(#id -> #'874543ca-2621-a14d-bb0e-8a0a48b49afa').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'5e465308-8af5-7b4f-9372-db5466573429').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '9 June 2015 10:03:06 am').
(#isNew -> false)}))})