steps
step1d5de9cf9877a84891b49715373f1ad1
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'947580ae-d1f5-2f4c-9c33-6314c8d48f67').
(#iconCode -> 'UiFugueIcons arrowStepIcon').
(#id -> #'1d5de9cf-9877-a848-91b4-9715373f1ad1').
(#label -> 'Senders in Queries').
(#next -> #'6d55d7d6-3c09-b044-b03a-0105386e67a4').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #senders).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 580)}))})