steps
stepc26af06617fd444898295f6396db27e7
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a4917562-2926-5645-9322-b89a3cefc7d3').
(#iconCode -> 'nil').
(#id -> #'c26af066-17fd-4448-9829-5f6396db27e7').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'65993183-1d44-6440-9ff3-b525244b1359').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:19:46 am').
(#isNew -> false)}))})