steps
step41a224d783bca848a1fcb3e16df604f9
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'baae0367-2eb9-2745-b6af-c747b95925ac').
(#iconCode -> 'nil').
(#id -> #'41a224d7-83bc-a848-a1fc-b3e16df604f9').
(#label -> nil).
(#next -> #'659bb790-ed7e-4a44-93d4-298862236d0b').
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #'8c0c7c2f-de5c-284d-9d9a-2d20961a1db5').
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 200)}))})