steps
step11680fd2f33fd14ab414ed7067db4d47
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'058d3529-d310-e847-b148-dadf47ff31b9').
(#iconCode -> 'nil').
(#id -> #'11680fd2-f33f-d14a-b414-ed7067db4d47').
(#label -> nil).
(#next -> #senders).
(#properties -> (Dictionary newFrom: {
(#copyOfStep -> #identity).
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '11 February 2014 1:01:49 pm').
(#priority -> 6760)}))})