steps
stepbcc2e4a5b8850c4b994daff86495a657
	<step>

	^ ((Dictionary new) add: (#definition->#'48da8a27-387c-0f46-81a9-61696fe5cfaa'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'pre'); add: (#isNew->false); add: (#creationTimeStamp->'27 May 2015 6:11:54 pm'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bcc2e4a5-b885-0c4b-994d-aff86495a657'); add: (#isReference->false); yourself)