steps
step133ffe7f85b861499f16aa358af45627
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a0a47b49-0961-064e-942a-ba912268c957').
(#iconCode -> 'nil').
(#id -> #'133ffe7f-85b8-6149-9f16-aa358af45627').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'f2dffe4f-0120-a841-9ac3-bf7dcdaa147d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 November 2017 9:34:46 am')}))})