steps
step959bb1be74008b46bbf7ad6fc02146e4
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQuerySortStep).
(#definition -> #'3d30f848-6623-6f4b-b599-ca6fffd99810').
(#iconCode -> 'nil').
(#id -> #'959bb1be-7400-8b46-bbf7-ad6fc02146e4').
(#label -> nil).
(#next -> #'d70ca6fc-bf5e-ee4a-ae39-89d3d351c3bb').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '28 August 2013 2:37:39 pm').
(#priority -> 1740)}))})