steps
stepGramadaDebuggerPane
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c6a7a923-06d5-ae42-b6ce-edf36178c3bf').
(#iconCode -> 'nil').
(#id -> #GramadaDebuggerPane).
(#isProperty -> true).
(#isReference -> false).
(#label -> 'Grammar Debugger').
(#next -> #'ce0a7522-9f8c-cb41-9347-ca73d724631d').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:10:29 pm').
(#fixedLayout -> true).
(#inputKind -> {OhmNode. OhmMatchFailure}).
(#optimalExtent -> (736@604)).
(#view -> ViMultiPaneTiled)}))})