steps
step478010d8a555dd4ea22a86f236aee014
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'4f13abce-d727-5143-a569-3a329c380f68').
(#iconCode -> 'nil').
(#id -> #'478010d8-a555-dd4e-a22a-86f236aee014').
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Recently Opened').
(#next -> #'c4ee7c1c-d764-1148-89be-c82a7c91889c').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '15 June 2015 9:17:12 am').
(#inputKind -> ViProfile).
(#isNew -> false).
(#notifier -> {[:t1 | ViObjectHistoryNotifier new history: t1 recentPackages]. [:t1 | ViObjectHistoryNotifier new history: t1 recentClasses]. [:t1 | ViObjectHistoryNotifier new history: t1 recentMethods]}).
(#view -> ViTreePlainView)}))})