steps
step30ef24b4df2f65489a1546d547ce5963
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'a634c657-feeb-3946-af60-a9629f97c504').
(#iconCode -> 'nil').
(#id -> #'30ef24b4-df2f-6548-9a15-46d547ce5963').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'133ffe7f-85b8-6149-9f16-aa358af45627').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 November 2017 9:34:46 am')}))})