steps
stepec27e35b91eeb94e9342baa884132c3d
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'8bbd1ad2-f7ff-344d-b98b-69f4cf799e1c').
(#iconCode -> 'nil').
(#id -> #'ec27e35b-91ee-b94e-9342-baa884132c3d').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> nil).
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '18 November 2015 4:05:02 pm').
(#inputKind -> OhmRule)}))})