steps
step8bf990f751e966498a24aa221296e3df
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'c6783154-3c97-1149-90b6-a99f91d1719a').
(#iconCode -> 'nil').
(#id -> #'8bf990f7-51e9-6649-8a24-aa221296e3df').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'86fb52a5-7259-b645-a22e-32277696081e').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 6:05:45 pm').
(#inputKind -> OhmMatchResult).
(#priority -> 2).
(#view -> ViButtonBarView)}))})