steps
step0d13b248416ec04ba5b7c1ea78d951f6
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'dd3789ab-5d56-b14e-aeb9-0b4f17e2b0d3').
(#iconCode -> 'nil').
(#id -> #'0d13b248-416e-c04b-a5b7-c1ea78d951f6').
(#isProperty -> false).
(#isReference -> false).
(#label -> nil).
(#next -> #'981d1d35-ca7a-d842-824c-b8c0e09bce59').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'087a9105-57dd-5b4e-880e-3cab7bc945a6').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '21 May 2017 5:59:38 pm').
(#inputKind -> TestCase class)}))})