steps
stepohmRuleActionsNormal
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'58aeeb13-02da-4545-bbde-10445a493d2d').
(#iconCode -> 'nil').
(#id -> #ohmRuleActionsNormal).
(#isProperty -> false).
(#isReference -> false).
(#label -> 'Rule actions').
(#next -> #'dc8a3ba9-b656-0e4f-ae77-27779ca5efaf').
(#properties -> (Dictionary newFrom: {
(#copyOf -> #'64adbb0a-e5c2-ba4a-ba47-ae28ab575d89').
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '1 June 2015 1:30:44 pm').
(#isNew -> false).
(#view -> ViArtifactListView2)}))})