steps
step31c9d76a803e8144b51e33d999326cee
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'cf912c09-38eb-284e-8046-321c9d214f2f').
(#iconCode -> 'nil').
(#id -> #'31c9d76a-803e-8144-b51e-33d999326cee').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'56e04d8b-f352-3c4a-80ba-83f5bf6d6e61').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '28 May 2015 10:20:30 am').
(#view -> ViMultiPaneTiled)}))})