steps
step6d7f9bea0e5cc94ca4cb7c20ea715fa8
	<step>

	^ (Dictionary newFrom: {
(#class -> ViQueryTransformStep).
(#definition -> #'720a8d90-f7c1-334e-a4ea-5094ba285a8d').
(#iconCode -> 'nil').
(#id -> #'6d7f9bea-0e5c-c94c-a4cb-7c20ea715fa8').
(#label -> nil).
(#next -> #'bc5c5199-b11b-5a4c-8363-dcfb005b4abf').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'mt').
(#creationTimeStamp -> '10 January 2014 12:51:11 pm').
(#priority -> 4650)}))})