steps
step659931831d4464409ff3b525244b1359
	<step>

	^ (Dictionary newFrom: {
(#class -> ViScriptPart).
(#definition -> #'38368f17-f259-ea4f-a77c-fe3f65f460fe').
(#iconCode -> 'nil').
(#id -> #'65993183-1d44-6440-9ff3-b525244b1359').
(#isProperty -> true).
(#isReference -> false).
(#label -> nil).
(#next -> #'cb27335f-db56-7846-b984-df3362a4ee99').
(#properties -> (Dictionary newFrom: {
(#creationAuthor -> 'pre').
(#creationTimeStamp -> '27 May 2015 5:33:51 pm').
(#isNew -> false)}))})