as yet unclassified
themeProperties
	
	^{	{#default . {Color black}} .
		{#ohmCommentKeyword . {Color green muchDarker . TextEmphasis italic}} .
		{#ohmCommentText . {Color green muchDarker . TextEmphasis italic}} .
		{#ohmRuleDeclarationName . {Color black . TextEmphasis bold}} .
		{#ohmOperator . {Color black}} .
		{#ohmRuleReferenceName . {Color blue}} .
		{#ohmAltCaseName . {Color gray lighter . TextEmphasis italic }} }	